# Generated by Django 5.1.4 on 2024-12-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200, verbose_name='Nome da categoria')),
                ('Classe', models.CharField(max_length=1, verbose_name='Classe')),
                ('Descricao', models.CharField(blank=True, max_length=900, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200, verbose_name='Nome do fornecedor')),
                ('Distancia', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Distancia')),
                ('Descricao', models.CharField(blank=True, max_length=900, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('Codigo_do_produto', models.CharField(max_length=200, unique=True, verbose_name='Código do produto')),
                ('Descricao', models.CharField(blank=True, max_length=900, verbose_name='Descrição')),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('Quantidade_em_estoque', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Quantidade em estoque')),
                ('Data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('Categorias', models.ManyToManyField(to='produtos.categoria')),
                ('Fornecedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fornecedor')),
            ],
        ),
    ]
